FORMAT: 1A
HOST: http://test.hazteunafacturae.com/api/v1/

# HazteUnaFacturae API

# Consideraciones generales

Esta documentación detalla las diferentes funciones que ofrece el JSON RESTful API de **HazteUnaFacturae**. 

## Autorización

Todas las peticiones al API requieren autorización. Dicha autenticación se realiza por medio de una cabecera HTTP llamada `Authorization` que tendrá el valor `Basic API_KEY` (tendrás que sustituir API_KEY por el valor real de tu clave).
Adicionalmente se podrá facilitar un usuario y contraseña a un servicio de login, lo que permitirá recuperar un USER_TOKEN, necesario para la realización de ciertas operaciones.

## Formatos

La respuesta es siempre en formato JSON. 

## Puntos básicos

+ **HTTPS**: Todas las peticiones se realizan sobre HTTPS.
+ **UTF-8 encoding**: Todas las cadenas se enviarán y recibirán en UTF-8.
+ **ISO Date format**: Los formatos de tipo Date y DateTime seguirán el formato ISO 8601:
    + Date: `2013-07-18`
    + DateTime: `2013-07-18T19:30:06.445Z`

## Métodos HTTP

Las peticiones siguen, en la medida de los posible, las directrices de un API REST. Esto significa que cada servicio soportará uno o más de los siguientes métodos HTTP:

+ `GET`. Recupera información sobre un recurso.
+ `POST`. Crea un recurso.
+ `PUT`. Actualiza un recurso.
+ `DELETE`. Elimina un recurso.

En esta documentación se enumeran a continuación qué métodos soportan los diferentes recursos de la plataforma.

## Códigos de Respuesta

El presente API utiliza los códigos de error estándar de HTTP para indicar que la ejecución de una petición ha sido errónea:

| Código | Descripción |
|--------|-------------|
| 200  | OK. |
| 201  | Creado. |
| 400  | Petición inválida. |
| 401  | No autorizado. Se ha enviado un token erróneo o el usuario identificado no puede ejecutar la acción. |
| 404  | No encontrado. |
| 500  | Error interno. Se ha producido un error en la ejecución de la acción solicitada |

Adicionalmente, en el cuerpo de la respuesta, cuando los códigos no son 200 o 201, se incluye siempre un código de error y un mensaje de error que describe más en detalle qué ha ocurrido.

## Códigos de error


| Excepción | Código de error |
|--------|-------------|
| INVALID_FACTURAE_FILE | 100
| INVALID_FACTURAE_MULTIPLE_INVOICES | 110 
| INVALID_FACTURAE_SCHEMA | 120
| INVALID_FACTURAE_SIGNED | 130
| INVALID_FACTURAE_VERSION | 140
| INVALID_INVOICE_SENDER | 150
| PGE_SENT_ERROR | 160
| INVALID_FORMAT | 170
| INVALID_APP_CREDENTIALS | 180
| INVALID_INVOICE_CODE | 190
| INVALID_APP_RESELLER | 200
| RESTRICTED_IP | 210
| INVALID_RECEIVER | 220
| INVALID_NUMBER_ATTACHMENTS | 230
| INVALID_ATTACHMENT | 240 
| INVALID_CSV_FILE_FORMAT | 250
| INVALID_CSV_FILE | 260
| SEARCH_NUMBER_RESULTS_EXCEEDED | 270
| CANCELLATION_ERROR | 280
| CANCELLATION_NOT_ALLOWED | 290
| UNEXPECTED_AUTH_ERROR | 300
| MANDATORY_DATA | 310
| JSON_BODY_NOT_FOUND | 310
| USER_BLOCKED | 320
| USER_INACTIVE | 330
| USER_INVALID | 340
| INVALID_REQUEST | 350
| ENTITY_NOT_FOUND | 360
| ENTITY_ALREADY_EXISTS | 370
| CUSTOMER_ALREADY_EXISTS | 380
| INVALID_ORG | 390
| INVALID_STATE | 490
| ORGANIZATION_ALREADY_EXISTS | 380
| INVALID_ORDER_CRITERIA | 510
| EXPORT_ERROR | 410
| INVALID_EXPORT_FORMAT | 420
| INVALID_DRAFT_STATE | 430
| MANDATORY_PASSWORD | 440
| EXISTING_USER | 450
| INVALID_SERIES_ID | 460
| BAD_PERMISSIONS | 470
| INVALID_ROLE_CODE | 480
| INVALID_ACTIVITY_ID | 490
| UNKNOWN_ERROR | S/N
 
 Estos códigos de error van acompañados de un mensaje que explica más en detalle cada caso concreto.


# Group Servicios

## User/Pass Authentication [/login]

Este servicio permite recuperar el USER_TOKEN de un determinado usuario, un identificador único que permitirá acceder a ciertas operaciones sólo autorizadas a usuarios con determinados roles.
Este USER_TOKEN deberá utilizarse en el resto de servicios como parte de la cabecera.

###  Login [GET /login?user_name=username&pass=pass]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY

+ Response 200 (application/json)

        { "data": {
        "user_name": "peter32",
        "user_token": "8d1c5f-847f-43ac-ac10-2603586ec3"},
        "error_code": "",
        "error_message": ""}

## Master tables [/tables]

Estos servicios permiten recuperar las tablas maestras de la aplicación.

### Listar Formas de pago [GET /tables/paymentmeans]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
 
        { "data":
        {
            "payment_means":
            {
                "10": "Pagaré No a la Orden",
                "11": "Cheque",
                "12": "Reposición",
            }
        },
        "error_code": "",
        "error_message": ""}


### Listar Roles [GET /tables/roles]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
 
        { "data":
        {
            "roles":
            {
               "Firma de documentos": "SIGN",
                "Dos acciones": "ACTIONS",
                "Admin Gestoría": "MANAGER",
            "Proveedor": "SUPPLIER"
            }
        },
        "error_code": "",
        "error_message": ""}


### Listar Tipos de Impuestos [GET /tables/taxes]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "data":
        {
            "taxes":
            {
                "10": "IECDPCAC",
                "11": "IIIMAB",
                "12": "ICIO",
                "13": "MVDN",
                "14": "IMSN",
            }
        },
        "error_code": "",
        "error_message": ""}


### Listar Unidades de medida [GET /tables/unitsofmeasure]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
 
        { "data":
        {
            "units_of_measure":
            {
                "10": "Bolsas",
                "11": "Bombonas",
                "12": "Botellas",
                "13": "Botes"
            }
        },
        "error_code": "",
        "error_message": ""}

### Listar Estados de factura [GET /tables/invoicestates]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "data":
        {
            "invoice_states":
            {
                "ED": "En edición",
                "EN": "Enviada",
                "AB": "Abierta",
                "AC": "Aceptada",
                "RC": "Rechazada"
            }
        },
        "error_code": "",
        "error_message": ""}

### Listar Canales de envío [GET /tables/deliverymethods]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "data":
        {
            "delivery_methods":
            {
                "PLATFORM": "Generada en plataforma",
                "MAIL": "Correo electrónico con adjunto",
                "FTP": "Envío a través de FTP",
                "AOC": "Envío a través de AOC",
                "FACe": "Envío a través de FACe",
            }
        },
        "error_code": "",
        "error_message": ""}

### Listar Formatos de factura [GET /tables/invoiceformats]

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "data":
        {
            "invoice_formats":
            {
                "PDF": "PDF firmado",
                "PAPER": "Factura en papel",
                "Facturae31": "Facturae v3.1",
                "Facturae32": "Facturae v3.2"
            }
        },
        "error_code": "",
        "error_message": ""}

## Organization [/organizations]

Representa una entidad fiscal, ya se trate de una persona jurídica (empresa) o física (autónomo).

+ Attributes (BaseOrganization)

### Recuperar empresa [GET /organizations/{id}]

Recupera la empresa asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseOrganizationResponse)

### Listar empresas [GET]

Recupera el listado de empresas existentes en el sistema.

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseOrganizationArrayResponse)

### Crear empresa [POST]

Registra una nueva empresa en el sistema

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (Organization)

+ Response 201 (application/json)

        {"data":
        {
        "id": "356"
        },
        "error_code": "",
        "error_message": ""}


### Actualizar empresa [PUT /organizations/{id}]

Actualiza una empresa existente en el sistema
+ Parameters
    + id (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (Organization)

+ Response 200 (application/json)

        {
        "error_code": "",
        "error_message": ""}


### Eliminar empresa [DELETE /organizations/{id}]

Elimina la empresa asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
  
        {
        "error_code": "",
        "error_message": ""}
        
### Actividad reciente [GET  /organizations/{orgId}/activity?num_results]

Recupera la actividad reciente generada por la empresa.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + num_results (number, optional) - cantidad de elementos a mostrar, si no informa se retornan 15

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

    + Attributes (BaseActivityArrayResponse)
    
### Eliminar actividad reciente [DELETE  /organizations/{orgId}/activity/{id}]

Elimina (marca como leída) una actividad.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador de la actividad

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
  
        {
        "error_code": "",
        "error_message": ""}


## Organization Configuration [/organizations/{id}/configuration]

Define la configuración estándar para el funcionamiento de una empresa. Cuando se crean nuevos clientes asociados a la empresa, se les asigna esta misma configuración por defecto, pudiendo luego configurarla de manera individual por cada uno de ellos.

+ Attributes (OrganizationConfiguration)
    
### Recuperar configuración [GET]

Recupera la configuración de la empresa asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (OrganizationConfigurationResponse)


### Actualizar configuración [PUT]

Actualiza la configuración por defecto para la empresa especificada

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (Organization Configuration)

+ Response 200 (application/json)
   
        {
        "error_code": "",
        "error_message": ""}
        
        
  
  
## Series [/organizations/{orgId}/series]

 Permite configurar las series y numeración de las facturas

+ Attributes (BaseSerie)

### Recuperar serie [GET /organizations/{orgId}/series/{id}]

Recupera la serie asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la serie
    + orgId (number) - identificador interno de la organización

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseSerieResponse)

### Listar series [GET]

Recupera el listado de series configuradas para la applicación que hace la solicitud.

+ Parameters
    + orgId (number) - identificador interno de la organización
    
+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseSerieArrayResponse)

### Crear serie [POST]

Registra una nueva serie en el sistema para la aplicación que hace la solicitud.

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (BaseSerie)

+ Response 201 (application/json)

        {"data":
        {
        "id": "356"
        },
        "error_code": "",
        "error_message": ""}


### Actualizar serie [PUT /organizations/{orgId}/series/{id}]

Actualiza una serie existente en el sistema
+ Parameters
    + id (number) - identificador interno de la serie
    + orgId (number) - identificador interno de la organización

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (BaseSerie)

+ Response 200 (application/json)
C
        {
        "error_code": "",
        "error_message": ""}


### Eliminar serie [DELETE organization/{orgId}/series/{id}]

Elimina la serie asociada al ID especificado.

+ Parameters
    + id (number) - identificador interno de la serie
    + orgId (number) - identificador interno de la organización

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
  
        {
        "error_code": "",
        "error_message": ""}

      
      
## User [/users]

Permiten la gestión de los usuarios de la plataforma.

+ Attributes (BaseUser)

### Recuperar usuario [GET /users/{id}]

Recupera el usuario asociado al ID especificado.
+ Parameters
    + id (number) - identificador interno del usuario

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseUserResponse)

### Listar usuarios [GET]

Recupera el listado de usuarios configurados para la applicación que hace la solicitud.

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseUserArrayResponse)

### Crear usuario [POST]

Registra un nuevo usuario.

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (BaseUser)

+ Response 201 (application/json)

        {"data":
        {
        "id": "356"
        },
        "error_code": "",
        "error_message": ""}


### Actualizar usuario [PUT /users/{id}]

Actualiza un usuario existente en el sistema
+ Parameters
    + id (number) - identificador interno del usuario

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (BaseUser)

+ Response 200 (application/json)

        {
        "error_code": "",
        "error_message": ""}


### Eliminar usuario [DELETE /users/{id}]

Elimina el usuario asociado al ID especificado.
+ Parameters
    + id (number) - identificador interno del usuario

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
  
        {
        "error_code": "",
        "error_message": ""}

      
## Customer [/organizations/{orgId}/customers]

Representa un cliente de la empresa identificada por el ID especificado.

+ Attributes (BaseCustomer)

### Recuperar cliente [GET /organizations/{orgId}/customers/{id}]

Recupera el cliente asociado al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del cliente

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseCustomerResponse)

### Listar clientes [GET /organizations/{orgId}/customers/{?customer_name,customer_tax_number,quick_search,sort_by,order,page,page_size}]

Recupera los clientes de la empresa.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + customer_name (string, optional) - nombre de cliente
    + customer_tax_number (string, optional) - nif de cliente
    + quick_search (string, optional) - término para búsqueda rápida en multiples campos: nombre, apellido, nif, email, dirección y provincia
    + sort_by (array[string], optional) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + page (number, optional) - número de página
    + page_size (number, optional) - cantidad de elementos por página

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
 
+ Response 200 (application/json)

       + Attributes (BaseCustomerArrayResponse)
        
### Exportar clientes [GET /organizations/{orgId}/customers/export{?customer_name,customer_tax_number,sort_by,order,export_format}]

Exporta los resultados de una búsqueda de clientes. Los formatos de exportación disponibles son: CSV, PDF, XLS, XLSX, DOCX, RTF, ODT, ODS.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + customer_name (string, optional) - nombre de cliente
    + customer_tax_number (string, optional) - nif de clienteados
    + sort_by (array[string], optional) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + export_format (string, required) - formato de exportación

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
 
+ Response 200 (application/json)
    + Attributes
       + export (string) - fichero con el resultado de la exportación condificado en Base64

### Top clientes [GET /organizations/{orgId}/customers/top/{?sort_by,order,number}]

Recupera una lista con un número limitado de clientes 'top' ordenados por un determinado criterio.

+ Parameters
    + sort_by (array[string], required) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + number (number, optional) - número de clientes del ranking
    
+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
 
+ Response 200 (application/json)

       + Attributes (BaseCustomerArrayResponse)
        

### Crear cliente [POST]

Registra un nuevo cliente asociado a la empresa

+ Parameters
    + orgId (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (Customer)

+ Response 201 (application/json)

        { "data":
        {
            "id": "665"
        },
        "error_code": "",
        "error_message": ""}



### Actualizar cliente [PUT /organizations/{orgId}/customers/{id}]

Actualiza un cliente

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del cliente

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (Customer)

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}

### Eliminar cliente [DELETE /organizations/{orgId}/customers/{id}]

Elimina el cliente asociado al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del cliente

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}

## Customer Configuration [/organizations/{orgId}/customers/{cusId}/configuration]

Define la configuración específica para un cliente.

+ Attributes (CustomerConfiguration)

### Recuperar configuración [GET]

Recupera la configuración del cliente asociado al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + cusId (number) - identificador interno del cliente

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (CustomerConfigurationResponse)


### Actualizar configuración [PUT]

Actualiza la configuración para el cliente especificado
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + cusId (number) - identificador interno del cliente

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (CustomerConfiguration)

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}


## Draft [/organizations/{orgId}/drafts]

Representa una factura en borrador.

+ Attributes (BaseInvoice)
    + id (number) - identificador interno

### Recuperar borrador [GET /organizations/{orgId}/drafts/{id}]

Recupera el borrador asociado al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del borrador de factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseDraftResponse)

### Listar facturas en borrador [GET]

Recupera las facturas en borrador de la empresa.

+ Parameters
    + orgId (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
   
       + Attributes (BaseDraftArrayResponse)

### Crear borrador [POST]

Crea un nuevo borrador de factura asociado a la empresa. El borrador se crea "vacío", tan solo debe indicarse el cliente al que se dirige, para en función de éste contruir la factura en el formato adecuado aplicando su configuración.
Para introducir el resto de datos de la factura puede utilizarse el método PUT y los métodos a nivel de líneas de factura.

+ Parameters
    + orgId (number) - identificador interno de la empresa

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes
        + cusId (number) - identificador del cliente al que se emitiría la factura

+ Response 201 (application/json)

        { "data":
        {
            "id": "665"
        },
        "error_code": "",
        "error_message": ""}


### Actualizar borrador [PUT /organizations/{orgId}/drafts/{id}]

Actualiza un borrador de factura

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del borrador de factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (DraftUpdatable)

+ Response 200 (application/json)
    + Attributes (BaseDraftResponse)

### Eliminar borrador [DELETE /organizations/{orgId}/drafts/{id}]

Elimina el borrador de factura asociado al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del borrador

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
        
        {"error_code": "",
        "error_message": ""}

### Enviar borrador [GET /organizations/{orgId}/drafts/{id}/send]

Envía un borrador de factura. El borrador (Draft) desaparece y da lugar a una factura (Invoice).

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador del borrador a enviar

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseInvoiceResponse)

### Previsualizar borrador [GET /organizations/{orgId}/drafts/{id}/preview]

Previsualiza en formato PDF el borrador de una factura.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador del borrador a previsualizar

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes
       + preview (string) - previsualización del borrador condificado en Base64
       
### Validar borrador [GET /organizations/{orgId}/drafts/{id}/validate]

Valida si el borrador dispone de toda la información necesaria para poder enviarse.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador del borrador a validar

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        {"data":
        {
            "invoice_errors":
            {
                "invoice.issueDate": "Fecha de emisión: Obligatorio"
            },
            "is_valid": "false"
        },
        "error_code": "",
        "error_message": "" }



## Draft Attachment [/organizations/{orgId}/drafts/{id}/attachments]

Representa un fichero adjunto.

+ Attributes (Attachment) 

### Listar adjuntos de borrador [GET /organizations/{orgId}/drafts/{id}/attachments]

Recupera un array con los identificadores de los ficheros adjuntos.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del borrador

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (AttachmentsArrayResponse)

### Recuperar adjunto [GET /organizations/{orgId}/drafts/{draftId}/attachments/{id}]

Recupera un fichero adjunto.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del borrador
    + id (number) - identificador interno del adjunto

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (AttachmentResponse)


### Subir adjunto [POST /organizations/{orgId}/drafts/{id}/attachments]

Permite subir un fichero adjunto a una factura en borrador.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno del borrador

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (AttachmentToUpload)

+ Response 200 (application/json)
    
        { "error_code": "",
        "error_message": ""}


### Eliminar adjunto [DELETE /organizations/{orgId}/drafts/{draftId}/attachments/{id}]

Permite eliminar un fichero adjunto de una factura en borrador.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del borrador
    + id (number) - identificador interno del adjunto

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            

+ Response 200 (application/json)
    
        { "error_code": "",
        "error_message": ""}


## Draft Item [/organizations/{orgId}/drafts/{draftId}/items]

Define las líneas de una factura en borrador.

+ Attributes (BaseItem)

### Crear línea de borrador [POST]

Crea una nueva línea dentro de un borrador de factura.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del borrador

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (BaseItem)

+ Response 201 (application/json)

    + Attributes (BaseItemResponse)

### Recuperar líneas [GET]

Recupera las líneas de una factura en borrador.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del borrador

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
 + Attributes (BaseItemArrayResponse)
       
### Recuperar línea [GET /organizations/{orgId}/drafts/{draftId}/items/{id}]

Recupera la información de una línea de un borrador
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del cliente
    + id (number) - identificador interno de la línea

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
+ Response 200 (application/json)
    + Attributes (BaseItemResponse)

### Actualizar línea [PUT /organizations/{orgId}/drafts/{draftId}/items/{id}]

Actualiza la línea especificada de un borrador
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del cliente
    + id (number) - identificador interno de la línea

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes (BaseItem)

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}



### Eliminar línea [DELETE /organizations/{orgId}/drafts/{draftId}/items/{id}]

Elimina una línea de un borrador de factura.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + draftId (number) - identificador interno del cliente
    + id (number) - identificador interno de la línea

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
 
        { "error_code": "",
        "error_message": ""}


## Sent Invoice [/organizations/{orgId}/invoices]

Representa una factura emitida.

+ Attributes (BaseInvoice)
    + id (number) - identificador interno
    + delivery_code (string) - código de registro asignado por el canal de envío
    + history (array[InvoiceHistory]) - historial de la factura

### Recuperar factura [GET /organizations/{orgId}/invoices/{id}]

Recupera la factura asociada al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (BaseInvoiceResponse)

### Listar facturas [GET  /organizations/{orgId}/invoices/{?invoice_number,series,date_from,date_to,customer_id,customer_name,customer_tax_number,item_description,payment_date,status,quick_search,sort_by,order,page,page_size}]

Recupera las facturas emitidas por la empresa.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + invoice_number (string, optional) - número de factura
    + series (string, optional) - número de serie
    + date_from (string, optional ) - fecha de factura desde
    + date_to (string, optional) - fecha de factura hasta
    + customer_id (number, optional) - identificador de cliente
    + customer_name (string, optional) - nombre de cliente
    + customer_tax_number (string, optional) - nif de cliente
    + item_description (string, optional) - descripción de línea
    + payment_date (string, optional) - fecha de pago
    + status (array[string], optional) - array de estados
    + quick_search (string, optional) - término de búsqueda rápida para múltiples campos: número, serie, cif, concepto
    + sort_by (array[string], optional) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + page (number, optional) - número de página
    + page_size (number, optional) - cantidad de elementos por página

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

    + Attributes (BaseInvoiceArrayResponse)
    
### Exportar facturas emitidas [GET  /organizations/{orgId}/invoices/export{?invoice_number,series,date_from,date_to,customer_id,customer_name,customer_tax_number,item_description,payment_date,status,sort_by,order,export_format}]

Exporta los resultados de una búsqueda de facturas emitidas. Los formatos de exportación disponibles son: CSV, PDF, XLS, XLSX, DOCX, RTF, ODT, ODS.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + invoice_number (string, optional) - número de factura
    + series (string, optional) - número de serie
    + date_from (string, optional ) - fecha de factura desde
    + date_to (string, optional) - fecha de factura hasta
    + customer_id (number, optional) - identificador de cliente
    + customer_name (string, optional) - nombre de cliente
    + customer_tax_number (string, optional) - nif de cliente
    + item_description (string, optional) - descripción de línea
    + payment_date (string, optional) - fecha de pago
    + status (array[string], optional) - array de estados
    + sort_by (array[string], optional) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + export_format (string, required) - formato de exportación

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "data": {"export":"23rjfsjfijgerkkdkfdkhfdk399reg9uq9u9uef9vs"},
        "error_code": "","error_message": "" }
        
       
### Actualizar estado de factura [PUT /organizations/{orgId}/invoices/{id}]

Actualiza el estado de una factura

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes
        + state (string) - nuevo estado de la factura

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}


### Eliminar factura [DELETE /organizations/{orgId}/invoices/{id}]

Elimina le factura asociada al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}


### Recuperar original [GET /organizations/{orgId}/invoices/{id}/original]

Recupera el fichero original de la factura asociada al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes
        + original (string) - original de la factura condificado en Base64
        
### Recuperar vista PDF [GET /organizations/{orgId}/invoices/{id}/pdf]

Recupera la vista en PDF de la factura asociada al ID especificado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes
        + pdf (string) - vista pdf condificada en Base64

### Aceptar factura [PUT /organizations/{orgId}/invoices/{id}/accept]

Marca una factura como aceptada por el receptor de la misma.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}

### Rechazar factura [PUT /organizations/{orgId}/invoices/{id}/reject]

Marca una factura como rechazada por el cliente.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN
            
    + Attributes
        + reason (string, required) - motivos de rechazo

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}

### Estadísticas [GET /organizations/{orgId}/invoices/statistics?num_months]

Recupera un array con los identificadores de los ficheros adjuntos.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + num_months (number) - número de meses de los que se desea extraer estadísticas

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (InvoiceStatisticArrayResponse)
    
### Total facturado [GET /organizations/{orgId}/invoices/total_invoiced{?date_from,date_to}]

Recupera el importe total facturado.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + date_from (date) - fecha desde
    + date_to (date) - fecha hasta

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        {"data": {
        "total": 1061652.6400000001
        },
        "error_code": "",
        "error_message": ""
        }
        
### Total pendiente [GET /organizations/{orgId}/invoices/total_expected{?date_from,date_to}]

Recupera el importe total pendiente de pago
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + date_from (date) - fecha desde
    + date_to (date) - fecha hasta

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        {"data": {
        "total": 1061652.6400000001
        },
        "error_code": "",
        "error_message": ""
        }
        
### Total pagado [GET /organizations/{orgId}/invoices/total_paid{?date_from,date_to}]

Recupera el importe total pagado
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + date_from (date) - fecha desde
    + date_to (date) - fecha hasta

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        {"data": {
        "total": 1061652.6400000001
        },
        "error_code": "",
        "error_message": ""
        }
        
### Total impagado [GET /organizations/{orgId}/invoices/total_unpaid{?date_from,date_to}]

Recupera el importe total impagado
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + date_from (date) - fecha desde
    + date_to (date) - fecha hasta

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        {"data": {
        "total": 1061652.6400000001
        },
        "error_code": "",
        "error_message": ""
        }
        
### Total fallido [GET /organizations/{orgId}/invoices/total_faulty{?date_from,date_to}]

Recupera el importe total de facturas fallidas
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + date_from (date) - fecha desde
    + date_to (date) - fecha hasta

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

        {"data": {
        "total": 1061652.6400000001
        },
        "error_code": "",
        "error_message": ""
        }
        

        
## Invoice Attachment [/organizations/{orgId}/invoices/{id}/attachments]

Representa un fichero adjunto.

+ Attributes (Attachment) 

### Listar adjuntos [GET /organizations/{orgId}/invoices/{id}/attachments]

Recupera un array con los identificadores de los ficheros adjuntos.
+ Parameters
    + orgId (number) - identificador interno de la empresa
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (AttachmentsArrayResponse)

### Recuperar adjunto [GET /organizations/{orgId}/invoices/{invoiceId}/attachments/{id}]

Recupera un fichero adjunto.

+ Parameters
    + orgId (number) - identificador interno de la empresa
    + invoiceId (number) - identificador interno de la factura
    + id (number) - identificador interno del adjunto

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)
    + Attributes (AttachmentResponse)

## Received Invoice [/organizations/{orgId}/received_invoices]

Representa una factura recibida.

+ Attributes (BaseInvoice)
    + id (number) - identificador interno
    + history (array[InvoiceHistory]) - historial de la factura

### Recuperar factura [GET /organizations/{orgId}/received_invoices/{id}]

Recupera la factura asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY

+ Response 200 (application/json)
    + Attributes (BaseInvoiceResponse)

### Listar facturas [GET /organizations/{orgId}/received_invoices/{?invoice_number,series,date_from,date_to,customer_name,customer_tax_number,supplier_id,supplier_name,supplier_tax_number,item_description,status,quick_search,sort_by,order,page,page_size}]

Recupera las facturas recibidas por la empresa.

+ Parameters
    + invoice_number (string, optional) - número de factura
    + series (string, optional) - número de serie
    + date_from (string, optional ) - fecha de factura desde
    + date_to (string, optional) - fecha de factura hasta
    + customer_name (string, optional) - nombre de cliente
    + customer_tax_number (string, optional) - nif de cliente
    + supplier_id (number, optional) - identificador de proveedor
    + supplier_name (string, optional) - nombre de proveedor
    + supplier_tax_number (string, optional) - nif de proveedor
    + item_description (string, optional) - descripción de línea
    + status (array[string], optional) - array de estados
    + quick_search (string, optional) - término de búsqueda rápida para múltiples campos: número, serie, cif, concepto
    + sort_by (array[string], optional) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + page (number, optional) - número de página
    + page_size (number, optional) - cantidad de elementos por página

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            user_token : USER_TOKEN

+ Response 200 (application/json)

    + Attributes (BaseInvoiceArrayResponse)
    
### Exportar facturas [GET /organizations/{orgId}/received_invoices/export{?invoice_number,series,date_from,date_to,customer_name,customer_tax_number,supplier_id,supplier_name,supplier_tax_number,item_description,status,quick_search,sort_by,order,export_format}]

Exporta los resultados de una búsqueda de facturas. Los formatos de exportación disponibles son: CSV, PDF, XLS, XLSX, DOCX, RTF, ODT, ODS.

+ Parameters
    + invoice_number (string, optional) - número de factura
    + series (string, optional) - número de serie
    + date_from (string, optional ) - fecha de factura desde
    + date_to (string, optional) - fecha de factura hasta
    + customer_name (string, optional) - nombre de cliente
    + customer_tax_number (string, optional) - nif de cliente
    + supplier_id (number, optional) - identificador de proveedor
    + supplier_name (string, optional) - nombre de proveedor
    + supplier_tax_number (string, optional) - nif de proveedor
    + item_description (string, optional) - descripción de línea
    + status (array[string], optional) - array de estados
    + sort_by (array[string], optional) - array de campos de ordenación
    + order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
    + export_format (string, required) - formato de exportación

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY

+ Response 200 (application/json)
    + Attributes
       + export (string) - fichero con el resultado de la exportación codificado en Base64

### Actualizar estado de factura [PUT /organizations/{orgId}/received_invoices/{id}]

Actualiza el estado de una factura

+ Parameters
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            
    + Attributes
        + status (string) - nuevo estado de la factura

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}


### Recuperar original [GET /organizations/{orgId}/received_invoices/{id}/original]

Recupera el fichero original de la factura asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY

+ Response 200 (application/json)
    + Attributes
        + original (string) - original de la factura codificado en Base64
        
### Recuperar vista PDF [GET /received_invoices/{id}/pdf]

Recupera la vista en PDF de la factura asociada al ID especificado.
+ Parameters
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY

+ Response 200 (application/json)
    + Attributes
        + pdf (string) - vista pdf codificada en Base64

### Aceptar factura [PUT /organizations/{orgId}/received_invoices/{id}/accept]

Marca una factura como aceptada.
+ Parameters
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}

### Rechazar factura [PUT /organizations/{orgId}/received_invoices/{id}/reject]

Marca una factura como rechazada.
+ Parameters
    + id (number) - identificador interno de la factura

+ Request (application/json)
    + Headers

            Authorization: Basic API_KEY
            
    + Attributes
        + reason (string, required) - motivos de rechazo

+ Response 200 (application/json)

        { "error_code": "",
        "error_message": ""}



# Data Structures

## AttachmentResponse (object)

+ data (Attachment) - contiene un objeto attachment
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error


## AttachmentsArrayResponse (object)

+ data (AttachmentsArray) - contiene un array de objetos Attachment (sin content)
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## AttachmentsArray (object)

+ attachments (array[BaseAttachment]) - array de adjuntos (sin content)

## OrganizationConfigurationResponse (object)

+ data (OrganizationConfiguration) - configuración base
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## OrganizationConfiguration (object)
+ currency (string, required) - código alpha de moneda
+ language (string, required) - código de idioma
+ invoice_format (string, required) - formato de factura por defecto
+ channel (string, required) - canal de envío de las facturas por defecto
+ bank_account (string, optional) - cuenta de cobro de las facturas por defecto
+ payment_deadline (number, optional) - periodo de cobro de las facturas por defecto
+ pdf_template (string, optional) - plantilla PDF a utilizar para las facturas
+ primary_color (string, optional) - color principal para la visualización en PDF (formato html)
+ secondary_color (string, optional) - color secundario para la visualización en PDF (formato html)
+ signature_delegated (boolean, required) - indica si la firma de la factura se delega en la plataforma
+ footer_texts (string, optional) - textos que se mostrarán por defecto en el pie de todas las facturas

## CustomerConfigurationResponse (object)

+ data (CustomerConfiguration) - configuración base
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## CustomerConfiguration (object)
+ currency (string, required) - código alpha de moneda
+ language (string, required) - código de idioma
+ invoice_format (string, required) - formato de factura por defecto
+ channel (string, required) - canal de envío de las facturas por defecto
+ bank_account (string, optional) - cuenta de cobro de las facturas por defecto
+ payment_deadline (number, optional) - periodo de cobro de las facturas por defecto
+ pdf_template (string, optional) - plantilla PDF a utilizar para las facturas


## BaseOrganizationResponse (object)

+ data (BaseOrganization) - contiene un objeto Organization
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseOrganizationArrayResponse (object)

+ data (BaseOrganizationArray) - contiene un array de objetos Organization
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseOrganizationArray (object)

+ organizations (array[BaseOrganization]) - empresas

## BaseOrganization (object)
+ tax_number (string, required) - número de identificación fiscal
+ name (string, required) - nombre
+ first_surname (string, optional) - primer apellido (para personas físicas)
+ second_surname (string, optional) - segundo apellido (para personas físicas)
+ address (string, required) - dirección postal
+ poblation (string, required) - población
+ province (string, required) - provincia
+ post_code (number, required) - código postal
+ country_code (string, required) - código Alpha3 de país
+ phone (string, optional) - número de teléfono
+ email (string, required) - dirección de correo electrónico
+ id (number) - identificador interno de la empresa
+ web_url (string, optional) - página web
+ logo (string, optional) - URL hacia el logotipo de la empresa

## BaseCustomer (object)
+ tax_number (string, required) - número de identificación fiscal
+ name (string, required) - nombre
+ first_surname (string, optional) - primer apellido (para personas físicas)
+ second_surname (string, optional) - segundo apellido (para personas físicas)
+ address (string, required) - dirección postal
+ poblation (string, required) - población
+ province (string, required) - provincia
+ post_code (number, required) - código postal
+ country_code (string, required) - código Alpha3 de país
+ phone (string, optional) - número de teléfono
+ email (string, required) - dirección de correo electrónico
+ id (number) - identificador interno del cliente
+ contact_person (string, optional) - persona de contacto en el cliente
    

## BaseCustomerResponse (object)

+ data (BaseCustomer) - contiene un objeto Customer
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseCustomerArrayResponse (object)

+ data (BaseCustomerArray) - contiene un array de objetos Customer
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseCustomerArray (object)

+ customers (array[BaseCustomer]) - clientes

## BaseTax (object)
+ tax_base (number, required) - base imponible
+ tax_rate (number, required) - porcentaje
+ tax_type (string, required) - tipo de impuesto a aplicar
+ tax_amount (number, optional) - importe

## BaseDiscount (object)
+ reason (string, required) - motivo de descuento
+ rate (number, optional) - porcentaje de dcto a aplicar
+ amount (number, required) - importe del dcto a aplicar

## BaseCharge (object)
+ reason (string, required) - motivo de cargo
+ rate (number, optional) - porcentaje de cargo a aplicar
+ amount (number, required) - importe del cargo a aplicar

## BasePayment (object)
+ payment_date (string, required) - fecha del pago
+ payment_method (string, required) - método de pago
+ amount (number, required) - importe del pago
+ bank_account (string, optional) - cuenta de abono/cargo, según corresponda; obligatoria para pagos por recibo o transferencia

## BaseItemResponse (object)

+ data (BaseItem) - contiene un objeto Draft Item
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseItemArrayResponse (object)

+ data (BaseItemArray) - contiene un array de objetos Draft Item
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseItemArray (object)

+ draft_items (array[BaseItem]) - líneas de borrador

## BaseItem (object)
+ order (number, required) - ordinal superior a 0 para identificar el item dentro de la factura (1,2,3...)
+ description (string, required) - concepto a facturar
+ quantity (number, required) - cantidad
+ unit_of_measure (string, optional) - unidad de medida
+ price (number, required) - precio unitario
+ total_cost (number, optional) - importe bruto sin impuestos `dato calculado por el sistema`
+ gross_amount (number, optional) - importe bruto sin impuestos después de aplicar cargos y descuentos `dato calculado por el sistema`
+ comments (string, optional) - observaciones
+ article_code (string, optional) - código de artículo
+ delivery_note_number (string, optional) - número de albarán
+ delivery_note_date (string, optional) - fecha de albarán
+ transaction_date (string, optional) - fecha de operación
+ period_start_date (string, optional) - periodo facturado, fecha de inicio
+ period_end_date (string, optional) - periodo facturado, fecha de fin
+ contract_reference (string, optional) - referencia al contrato
+ transaction_reference (string, optional) - número de pedido
+ file_reference (string, optional) - referencia del expediente
+ taxes (array[BaseTax], optional) - impuestos
+ discounts (array[BaseDiscount], optional) - descuentos
+ charges (array[BaseCharge], optional) - cargos

## InvoiceHistory
+ id (number) - identificador interno de la historia
+ date (string, required) - fecha en que se produjo el evento
+ action (string, required) - acción realizada sobre la factura
+ initial_state (string, required) - estado inicial de la factura, antes de la acción
+ end_state (string, required) - estado final de la factura después de la acción
+ user (string, optional) - usuario, empresa o sistema autor de la acción
+ message (string, optional) - mensaje de rechazo, error o detalle de la acción realizada
+ ip (string, optional) - ip desde la que se ejecuta la acción
+ browser (string, optional) - navegador desde el que se ejecuta la acción
+ user_agent (string, optional) - cabecera user-agent del dispositivo desde el que se ejecuta la acción

## InvoiceActivity
+ id (number) - identificador interno de la historia
+ date (string, required) - fecha en que se produjo el evento
+ action (string, required) - acción realizada sobre la factura
+ initial_state (string, required) - estado inicial de la factura, antes de la acción
+ end_state (string, required) - estado final de la factura después de la acción
+ user (string, optional) - usuario, empresa o sistema autor de la acción
+ message (string, optional) - mensaje de rechazo, error o detalle de la acción realizada
+ ip (string, optional) - ip desde la que se ejecuta la acción
+ browser (string, optional) - navegador desde el que se ejecuta la acción
+ user_agent (string, optional) - cabecera user-agent del dispositivo desde el que se ejecuta la acción
+ invoice_id (number) - id de factura
+ invoice_number (string) - número de la factura

## BaseDraftResponse (object)

+ data (BaseInvoice) - contiene un objeto Draft
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseDraftArrayResponse (object)

+ data (BaseDraftArray) - contiene un array de objetos Draft
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseDraftArray (object)

+ drafts (array[BaseInvoice]) - borradores

## BaseInvoiceResponse (object)

+ data (BaseInvoice) - contiene un objeto Invoice
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseInvoiceArrayResponse (object)

+ data (BaseInvoiceArray) - contiene un array de objetos Invoice
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseInvoiceArray (object)

+ invoices (array[BaseInvoice]) - facturas

## BaseActivityArrayResponse (object)

+ data (BaseActivityArray) - contiene un array de objetos InvoiceHistory
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseActivityArray (object)

+ activity (array[InvoiceActivity]) - actividad reciente


## BaseInvoice (object)
+ number (string, required) - número de factura
+ series (string, optional) - número de serie
+ date (string, required) - fecha de factura
+ state (string, required) - código de estado
+ total_cost (number, required) - importe bruto sin impuestos `dato calculado por el sistema`
+ gross_amount (number, required) - importe bruto sin impuestos después de aplicar cargos y descuentos `dato calculado por el sistema`
+ total_to_pay (number, required) - total a pagar `dato calculado por el sistema`
+ currency (string, required) - moneda
+ comments (string, optional) - observaciones
+ sender (BaseOrganization, optional) - emisor de la factura
+ receiver (BaseCustomer, optional) - receptor de la factura
+ items (array[BaseItem]) - líneas de factura
+ payments (array[BasePayment]) - vencimientos
+ taxes (array[BaseTax]) - impuestos
+ discounts (array[BaseDiscount]) - descuentos
+ charges (array[BaseCharge]) - cargos
+ exchange_rate (number, optional) - tipo de cambio
+ invoice_type (string, required) - tipo de factura original o rectificativa (valores OO y OR respectivamente)
+ corrective_start_date (string, optional) - fecha inicio de factura rectificativa
+ corrective_end_date (string, optional) - fecha fin de factura rectificativa
+ corrective_inv_number (number, optional) - número de factura rectificada
+ corrective_inv_series (string, optional) - serie de factura rectificada
+ corrective_reason_code (string, optional) - motivo de rectificación
+ corrective_reason_method (string, optional) - criterio de rectificación

## InvoiceCriteria
+ invoice_number (string, optional) - número de factura
+ series (string, optional) - número de serie
+ date_from (string, optional ) - fecha de factura desde
+ date_to (string, optional) - fecha de factura hasta
+ customer_id (number, optional) - identificador de cliente
+ customer_name (string, optional) - nombre de cliente
+ customer_tax_number (string, optional) - nif de cliente
+ item_description (string, optional) - descripción de línea
+ payment_date (string, optional) - fecha de pago
+ status (array[string], optional) - array de estados
+ sort_by (array[string], optional) - array de campos de ordenación
+ order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
+ page (number, optional) - número de página
+ page_size (number, optional) - cantidad de elementos por página

## CustomerCriteria
+ customer_id (number, optional) - identificador de cliente
+ customer_name (string, optional) - nombre de cliente
+ customer_tax_number (string, optional) - nif de clienteados
+ sort_by (array[string], optional) - array de campos de ordenación
+ order (string, optional) - ordenación ascendente (ASC) o descendente (DESC)
+ page (number, optional) - número de página
+ page_size (number, optional) - cantidad de elementos por página

## Attachment
+ content (string) - contenido del fichero adjunto condificado en Base64
+ name (string) - nombre del fichero (ej. fotocopia.pdf)
+ mime (string) - mime del fichero (ej. application/pdf)
+ id (number, required) - identificador del adjunto

## AttachmentToUpload
+ content (string) - contenido del fichero adjunto condificado en Base64
+ name (string) - nombre del fichero (ej. fotocopia.pdf)
+ mime (string) - mime del fichero (ej. application/pdf)

## BaseAttachment
+ name (string) - nombre del fichero (ej. fotocopia.pdf)
+ mime (string) - mime del fichero (ej. application/pdf)
+ id (number, required) - identificador del adjunto

## DraftUpdatable (object)
+ number (string, required) - número de factura
+ series (string, optional) - número de serie
+ series_id (number, optional) - id de la numeración/series a aplicar
+ date (string, required) - fecha de factura
+ comments (string, optional) - observaciones
+ payments (array[BasePayment]) - vencimientos
+ discounts (array[BaseDiscount]) - descuentos
+ charges (array[BaseCharge]) - cargos
+ exchange_rate (number, optional) - tipo de cambio
+ invoice_type (string, required) - tipo de factura original o rectificativa (valores OO y OR respectivamente)
+ corrective_inv_number (number, optional) - número de factura rectificada
+ corrective_inv_series (string, optional) - serie de factura rectificada
+ corrective_start_date (string, optional) - fecha inicio de factura rectificativa
+ corrective_end_date (string, optional) - fecha fin de factura rectificativa
+ corrective_reason_code (string, optional) - motivo de rectificación
+ corrective_reason_method (string, optional) - criterio de rectificación

## BaseSerieResponse (object)

+ data (BaseSerie) - contiene un objeto Serie
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseSerieArrayResponse (object)

+ data (BaseSerieArray) - contiene un array de objetos Serie
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseSerieArray (object)

+ series (array[BaseSerie]) - series

## BaseSerie (object)
+ id (number, optional) - id
+ code (string, required) - código que se introducirá en el campo serie de la factura
+ name (string, optional) - nombre
+ prefix (string, optional) - prefijo (puedes introducir los cuatro o dos dígitos del año, respectivamente, escribiendo las variables #AAAA# o #AA#)
+ suffix (string, optional) - sufijo (pueden utilizarse las mismas variables que en el caso anterior)
+ fill_left (number, optional) - longitud del número de factura
+ numbering (boolean, required) - determina si habrá numeración automática o no
+ default_series (boolean, optional) -  serie por defecto
+ reboot_year (boolean, optional) - reiniciar automáticamente con el cambio de año
+ next_number (number, optional) - siguiente número


## BaseUserResponse (object)

+ data (BaseUser) - contiene un objeto User
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseUserArrayResponse (object)

+ data (BaseUserArray) - contiene un array de objetos User
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## BaseUserArray (object)

+ users (array[BaseUser]) - usuarios

## BaseUser (object)
+ id (number, optional) - id
+ login (string, required) - nombre de usuario
+ name (string, required) - nombre
+ surname (number, optional) - apellido
+ email (string, optional) - email
+ roles (array[string]) - roles

## InvoiceStatisticArrayResponse (object)

+ data (InvoiceStatisticArray) - contiene un array de objetos InvoiceStatistic
+ error_message (string) - mensaje de error
+ error_code (number) - codigo de error

## InvoiceStatisticArray (object)

+ statistics (array[InvoiceStatistic]) - estadísticas

## InvoiceStatistic (object)
+ month (string) - mes
+ total_invoiced (number) - total facturado
+ total_paid (number) - total pagado
+ total_unpaid (number) - total impagado